spring.application.name=Transactions



# PostgreSQL Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=password

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Paystack config (direct value for development)
paystack.secret.key=sk_test_6d4411ab4887dce0e39133066ad7130ca1d85c69
paystack.public.key=PAYSTACK_PUBLIC_KEY=pk_test_7cc6f7bce630c85c2d14bf4981c19b198a31cefe

paystack.base.url=https://api.paystack.co
paystack.webhook.secret=whsec_your_webhook_secret_here
paystack.callback=http://localhost:8080/api/transactions/webhook
x-paystack-signature=18a751b19fb7279a2893e50ac3904f4b6f3a655adb15d407b03c133b9609c9a7





